code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.code-runner
code --install-extension graphql.vscode-graphql
code --install-extension hashicorp.terraform
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension msjsdiag.vscode-react-native
code --install-extension nucllear.vscode-extension-auto-import
code --install-extension pmneo.tsimporter
code --install-extension prisma.prisma
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension vscode-icons-team.vscode-icons
code --install-extension zxh404.vscode-proto3zxh404.vscode-proto3
code --install-extension xabikos.reactsnippets
code --install-extension redis.redis-for-vscode
code --install-extension yoavbls.pretty-ts-errors
code --install-extension mylesmurphy.prettify-ts
